export {
  isAdminEmail,
  resolveRole,
  canAccessModule,
  getEffectiveModules,
  MODULE_LABELS,
  moduleForPath,
  LOCKED_MODULES,
  // Salesforce Academy feature model (admin-controlled per-user access).
  LEARNING_CATEGORIES,
  LEARNING_CATEGORY_LABELS,
  LEARNING_CATEGORY_TAGLINES,
  LEARNING_CAPABILITIES,
  LEARNING_CAPABILITY_LABELS,
  LEARNING_CAPABILITY_DESCRIPTIONS,
  LEARNING_FEATURES,
  DEFAULT_LEARNING_FEATURES,
  categoryFeature,
  capabilityFeature,
  isLearningFeature,
  resolveLearningFeatureAccess,
  hasLearningCategory,
  hasLearningCapability,
  type AppModule,
  type UserRole,
  type UserAccessProfile,
  type LearningCategory,
  type LearningCapability,
  type LearningFeature,
  type LearningFeatureAccess,
} from '@sfcc/shared';
