export {
  isAdminEmail,
  resolveRole,
  canAccessModule,
  getEffectiveModules,
  MODULE_LABELS,
  MODULE_DESCRIPTIONS,
  isRegisteredAppPath,
  moduleForPath,
  LOCKED_MODULES,
  DEFAULT_USER_MODULES,
  REVOCABLE_DEFAULT_MODULES,
  type AppModule,
  type UserRole,
  type UserAccessProfile,
} from '@sfcc/shared';
